In [2]:
import polars as pl

In [4]:
image_path = "/mnt/czolab-storage-01/acruzcar/MAINCE_output/Cohort2_v2/V01/QC/Images/Measurements/Image.txt"

df = pl.read_csv(image_path, separator='\t')
df

shape: (7_776, 83)
┌───────────┬───────────┬───────────┬───────────┬───┬───────────┬───────────┬───────────┬──────────┐
│ Count_Cel ┆ Count_Ill ┆ Count_Ill ┆ Count_Nuc ┆ … ┆ Intensity ┆ Metadata_ ┆ Metadata_ ┆ Metadata │
│ ls        ┆ um_artifa ┆ um_artifa ┆ lei       ┆   ┆ _UpperQua ┆ Field     ┆ Plate     ┆ _Well    │
│ ---       ┆ cts       ┆ cts_filte ┆ ---       ┆   ┆ rtileInte ┆ ---       ┆ ---       ┆ ---      │
│ f64       ┆ ---       ┆ red       ┆ f64       ┆   ┆ nsi…      ┆ i64       ┆ i64       ┆ str      │
│           ┆ f64       ┆ ---       ┆           ┆   ┆ ---       ┆           ┆           ┆          │
│           ┆           ┆ f64       ┆           ┆   ┆ f64       ┆           ┆           ┆          │
╞═══════════╪═══════════╪═══════════╪═══════════╪═══╪═══════════╪═══════════╪═══════════╪══════════╡
│ 70.0      ┆ 4.0       ┆ 4.0       ┆ 73.0      ┆ … ┆ 0.131762  ┆ 9         ┆ 14        ┆ G04      │
│ 42.0      ┆ 5.0       ┆ 5.0       ┆ 43.0      ┆ … ┆ 0.063005  ┆ 8         ┆ 14        ┆ C05      │
│ 69.0      ┆ 0.0       ┆ 0.0       ┆ 69.0      ┆ … ┆ 0.132631  ┆ 1         ┆ 14        ┆ G04      │
│ 91.0      ┆ 1.0       ┆ 1.0       ┆ 92.0      ┆ … ┆ 0.131319  ┆ 7         ┆ 14        ┆ B12      │
│ 101.0     ┆ 1.0       ┆ 1.0       ┆ 106.0     ┆ … ┆ 0.165438  ┆ 3         ┆ 14        ┆ F01      │
│ …         ┆ …         ┆ …         ┆ …         ┆ … ┆ …         ┆ …         ┆ …         ┆ …        │
│ 99.0      ┆ 2.0       ┆ 2.0       ┆ 102.0     ┆ … ┆ 0.150149  ┆ 6         ┆ 18        ┆ A01      │
│ 78.0      ┆ 2.0       ┆ 2.0       ┆ 79.0      ┆ … ┆ 0.122087  ┆ 5         ┆ 18        ┆ C06      │
│ 83.0      ┆ 2.0       ┆ 2.0       ┆ 84.0      ┆ … ┆ 0.127153  ┆ 7         ┆ 18        ┆ B03      │
│ 74.0      ┆ 1.0       ┆ 1.0       ┆ 77.0      ┆ … ┆ 0.103166  ┆ 3         ┆ 18        ┆ F10      │
│ 76.0      ┆ 2.0       ┆ 2.0       ┆ 78.0      ┆ … ┆ 0.102708  ┆ 1         ┆ 18        ┆ H11      │
└───────────┴───────────┴───────────┴───────────┴───┴───────────┴───────────┴───────────┴──────────┘

In [24]:
sorted(df['Metadata_Plate'].unique())

[10, 11, 12, 13, 14, 15, 16, 17, 18]

In [19]:
df1 = df.group_by(['Metadata_Plate', 'Metadata_Well']).agg()
df1

shape: (864, 2)
┌────────────────┬───────────────┐
│ Metadata_Plate ┆ Metadata_Well │
│ ---            ┆ ---           │
│ i64            ┆ str           │
╞════════════════╪═══════════════╡
│ 11             ┆ D07           │
│ 11             ┆ D09           │
│ 10             ┆ C06           │
│ 14             ┆ D11           │
│ 14             ┆ H10           │
│ …              ┆ …             │
│ 11             ┆ E04           │
│ 10             ┆ G01           │
│ 16             ┆ C09           │
│ 11             ┆ C06           │
│ 11             ┆ G12           │
└────────────────┴───────────────┘

In [23]:
df.group_by(['Metadata_Plate','Metadata_Well','Metadata_Field']).agg()

shape: (7_776, 3)
┌────────────────┬───────────────┬────────────────┐
│ Metadata_Plate ┆ Metadata_Well ┆ Metadata_Field │
│ ---            ┆ ---           ┆ ---            │
│ i64            ┆ str           ┆ i64            │
╞════════════════╪═══════════════╪════════════════╡
│ 10             ┆ F11           ┆ 4              │
│ 13             ┆ H10           ┆ 5              │
│ 18             ┆ H01           ┆ 8              │
│ 14             ┆ E09           ┆ 7              │
│ 13             ┆ G10           ┆ 8              │
│ …              ┆ …             ┆ …              │
│ 10             ┆ G05           ┆ 3              │
│ 18             ┆ B02           ┆ 8              │
│ 14             ┆ E09           ┆ 2              │
│ 10             ┆ B11           ┆ 8              │
│ 13             ┆ C08           ┆ 8              │
└────────────────┴───────────────┴────────────────┘